name: Notify Main Repo
on:
  push:
    branches:
      - slug
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Main Repo Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/hyperlook/quartz/dispatches \
            -d '{"event_type":"submodule_updated"}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}